version: '3.1'

services:
  spark-db:
    container_name: spark-db
    image: mariadb
    ports:
      - "3306:3306"
    networks:
      - base_network
    volumes:
      - db_data:/var/lib/mysql
    env_file: .env

  spark-api:
    container_name: spark-api
    image: 'node'
    networks:
      - base_network
    ports:
      - '3000:3000'
    command: sh -c "yarn install && yarn start:dev"
    depends_on:
      - spark-db
    working_dir: /app
    volumes:
      - ./spark-api:/app
    env_file: .env

networks:
  base_network:

volumes:
  db_data: